### ISSUE TITLE
 项目里module 太多，有二级目录，比如:modules:umeng_bbs 这挂了 把本地的library 当成了maven坐标

### ISSUE THREAD

**Issue by pokercc** [mqzhangw/JIMU#10]
项目里module 太多，有二级目录，比如:modules:umeng_bbs 这挂了 把本地的library 当成了maven坐标
下面是gradle plugin 里的关键代码
![wyrs 68a in kv82e zf](https://user-images.githubusercontent.com/17515825/37952006-fc2544da-31d0-11e8-9908-b122ba0db78f.png)

**Comment by mqzhangw** [comment]
已经合并你的pr了，谢谢啦
