### ISSUE TITLE
Kotlin+DataBinding+JIMU遇到的问题

### ISSUE THREAD

**Issue by lhalcyon** [mqzhangw/JIMU#13]
如题, 目前我是将项目分成
app (host)
app-1
app-2
...
这样的模块化.   之前在集成项目时写了个demo 各module均可单独运行, host也可运行.  但是最近开发时出现了问题.  只要app 依赖  app-x   就会报错
![image](https://user-images.githubusercontent.com/21357951/38198354-078ef9e0-36bf-11e8-8fa9-a87734bd6fcc.png)
Btw , 路由用的阿里的ARouter

**Comment by lhalcyon** [comment]
顺便说下. vm 是我databinding xml文件中得变量名称 ,  已经再三检查没有写错,写串 . app 依赖 app 1- 3 就出问题   app 1-3  依赖 app-login单独运行都没有问题. ~  囧

**Comment by leobert-lan** [comment]
so sorry for too late to answer. 如果方便的话，是否可以提供下app app-1 app-2的build.gradle 以及 local.properties

**Comment by Licarey** [comment]
@lhalcyon 你好 能方便加下qq么 我遇到和你一样的问题 313685617

**Comment by lhalcyon** [comment]
@Licarey 不好意思,时间有点长,忘记怎么解决的了

**Comment by Licarey** [comment]
@lhalcyon 我解决了 我改了项目的module包名 就好了

**Comment by lhalcyon** [comment]
呃.解决了就好.发现kotlin+databinding 是不大好用. 加上组件化更不大好用
