### ISSUE TITLE
uirouter1.0.0版本集成问题

### ISSUE THREAD

**Issue by walnutt** [mqzhangw/JIMU#15]
按照readme集成后，，不能生成UIRouterTable及UI跳转

**Comment by leobert-lan** [comment]
在讨论群中，我收集了issue提出者的实际场景，这里补充一下：
baselib
![baselib](https://user-images.githubusercontent.com/15627746/38462211-6f38ab36-3b15-11e8-916d-ead4f34484dd.png)

包含目标Activity的module，实际上是一个kotlin和java混编的Module：
![image](https://user-images.githubusercontent.com/15627746/38462224-bb36117c-3b15-11e8-92e5-2f06a9560ae7.png)

目标Activity
![目标Activity](https://user-images.githubusercontent.com/15627746/38462207-4e6ff634-3b15-11e8-9095-4decba32a857.png)

--
我们发现：
* 这里并没有按照kotlin代码需要的方式集成注解处理器
* 我之前升级了as到3.1，kotlin1.2.21携带的kapt插件已跪（初步判断可能存在版本适配原因，还在排查中）
* 即使正确为kotlin集成了annotation处理器，也会出现覆盖的问题，这是设计时的一个bug，没有考虑到在一个Module中进行混编（生成的类将会同名，要么抛错要么会被覆盖），在问题未解决前，请各位暂时不要在一个Module中进行混编。这个问题我会持续跟进。

**Comment by leobert-lan** [comment]
按照kotlin官方文档，混编的Module使用kpat即可，会同时处理java和kotlin中的注解

**Comment by Weightang** [comment]
还有问题，在kotlin代码中，目标页面传参，用了Autowired注解，会编译错误，提示要：这个属性不能为私密的，但是我并没有设置私密属性？

**Comment by leobert-lan** [comment]
kotlin中声明的成员在使用Autowired时需要添加@JvmField注解。

**Comment by Weightang** [comment]
好的，谢谢
