### ISSUE TITLE
雷同

### ISSUE THREAD

**Issue by zxxcos** [mqzhangw/JIMU#16]
https://github.com/luojilab/DDComponentForAndroid；请问这两个账户是一样的，还是不一样，你们到底谁是原创，主页完全一样。
    还有能不能有点耐心，我提出一个疑问而已，你抄袭就抄袭，没抄袭就没抄袭，为什么直接关闭我的Issue！都是成年人了，不是都是一个人，别把自己搞得跟畜生似的！！！！

**Comment by mqzhangw** [comment]
...你能不能看看文章和commit记录，上个issue不是回答你了吗？

**Comment by mqzhangw** [comment]
这套方案是我在得到开发并开源的项目，现在我已经离职得到，不方便在原库上继续提交，所以移到这里继续维护了，在文章和上个issue都有说明。

**Comment by zjxuzhj** [comment]
这位大哥真是暴脾气。。。

**Comment by liyujiang-gzu** [comment]
> 这套方案是我在得到开发并开源的项目，现在我已经离职得到，不方便在原库上继续提交，所以移到这里继续维护了，在文章和上个issue都有说明。

这个总算释疑了，我觉得可以在README.md里提一下和[DDComponentForAndroid](https://github.com/luojilab/DDComponentForAndroid)的前世今生
