### ISSUE TITLE
comgradle插件1.2.0，找不到aar文件

### ISSUE THREAD

**Issue by zxhandroid** [mqzhangw/JIMU#17]
组件中使用的aar文件，在组件内部能单独编译通过，但在Host中编译却报找不到aar文件！！

**Comment by mqzhangw** [comment]
组件是通过aar方式提供给host的吗？还是直接用的project的方式？

**Comment by zxhandroid** [comment]
aar的方式，host当中并没有使用到aar中的类，为什么还会报找不到？
