### ISSUE TITLE
Jenkins编译，组件打包失败

### ISSUE THREAD

**Issue by wobuaihuangjun** [mqzhangw/JIMU#18]
本地编译项目没问题，但是在Jenkins编译，发现所有组件都没有打包进apk。

**Comment by leobert-lan** [comment]
我使用jenkins进行了一下情况的模拟，没有配置过于复杂的东西。用的JIMUDemo进行的测试，手动添加了local.properties避免检验jitpack上传任务读取不到文件的问题。jenkins中直接使用gradle assembleDebug编译app Module，生成了app-debug.apk,安装测试后并没有出现该问题。
请按照以下进行测试：

- 是否忽略了gradle.properties导致无法生成依赖。
- 检查jenkins中关于打包的核心命令。必要时可以手工验证。

**Comment by mqzhangw** [comment]
一般都是配置问题，仔细检查应该就可以解决了
