### ISSUE TITLE
400 from server: Bad Request

### ISSUE THREAD

**Issue by zhoujingheng** [mqzhangw/JIMU#29]
Could not GET 'https://dl.google.com/dl/android/maven2/com/github/jimu/build-gradle/1.3.2/build-gradle-1.3.2.pom'. Received status code 400 from server: Bad Request
Enable Gradle 'offline mode' and sync project

**Comment by AnthonyCoder** [comment]
@zhoujingheng  解决了吗 大哥

**Comment by leobert-lan** [comment]
sorry for too late

https://mvnrepository.com/artifact/com.github.jimu/build-gradle  可能你的配置或者网络有点问题，library一直发布在jcenter的，看你的地址像是走了google仓库。如果是工作环境的网络问题的话，我建议搭一个私有的maven仓库。将library传到私有仓库上。
