### ISSUE TITLE
E:\YzProject\YzLive\app\build\intermediates\transforms\desugar\debug\0.jar 

### ISSUE THREAD

**Issue by Yuphee** [mqzhangw/JIMU#31]
改了东西不clean直接运行老是报这个是什么问题

**Comment by Yuphee** [comment]
提示是不能删除

**Comment by ouyangpeng** [comment]
想问问   stop_gradle.bat 如何在安装apk之后 执行，这样就可以解除文件占用了。

@leobert-lan @mqzhangw

**Comment by yang1271772302** [comment]
Terminal执行命令gradlew -stop

**Comment by leobert-lan** [comment]
> Terminal执行命令gradlew -stop

哪怕时至今日，对于这类问题我也想不到比这个更好的办法。饮鸩止渴的话就直接配置不需要守护进程，用完gradle就让其死去。

客观条件允许的话，直接用mac或者Linux也能解决这个问题。对于Windows我不是太懂，像是进程持有文件读写句柄，但看起来很不合理。
