### ISSUE TITLE
导入编译遇到了Unknown host 'd29vzk4ow07wi7.cloudfront.net'. You may need to adjust the proxy settings in Gradle.

### ISSUE THREAD

**Issue by lintianlin** [mqzhangw/JIMU#36]
导入项目，编译遇到了这个错误：Unknown host 'd29vzk4ow07wi7.cloudfront.net'. You may need to adjust the proxy settings in Gradle.

**Comment by lintianlin** [comment]
https://www.jianshu.com/p/66baf3e58c6a

**Comment by leobert-lan** [comment]
cloudfront是Amazon的cdn，连接不上的话都是网络环境问题。遇到这种情况先ping一下，看看解析出来IP是啥，如果排除自己配置了错误的hosts、无效的proxy、基本就是运营商问题、域名解析服务器问题等等, 和项目本身是没有关系的。之前没看邮箱，没注意到issue。
