### ISSUE TITLE
关于component R资源问题及databinding问题。

### ISSUE THREAD

**Issue by YummyLau** [mqzhangw/JIMU#37]
如果单独运行conponent，则每次生成的databing再切回去运行app时会报错。
如果耽误运行component，则每次在类比如activity中需要导入当前R文件，在运行app时会报错。
希望作者百忙之中能看下，

**Comment by leobert-lan** [comment]
对于一些会生成的东西，例如apt，r类，在切换运行环境时都是会面临一些“编译缓存”问题的。

**Comment by YummyLau** [comment]
嗯嗯明白。再请教一个问题，uirouter其实做到了组件间页面的跳转，其他有一些“组件”只是一个服务，比如imageloader，这些服务的暴露是否考虑router来实现。另外，此类的组件是否也能做到代码隔离。

**Comment by leobert-lan** [comment]
其实对于UIrouter的实现我并不太满意。

其实正常路数应该是使用组件服务接口来隔离的(不过严格意义上讲，组建对象模型对外暴露的服务接口给组件内部使用不太像样)，不过比较“啰嗦”，所以我当时提供了uirouter。

对于一些常见的lib(glide，okhttp)可以直接下沉到基础库module中，直接使用，或者另写一个module，用组件服务接口对外暴露特定业务，隐藏实现，这样更加规范，比如说切换glide或者Picasso对于项目的影响几乎为0。

**Comment by leobert-lan** [comment]
其实对于UIrouter的实现我并不太满意。

其实正常路数应该是使用组件服务接口来隔离的(不过严格意义上讲，组建对象模型对外暴露的服务接口给组件内部使用不太像样)，不过比较“啰嗦”，所以我当时提供了uirouter。

对于一些常见的lib(glide，okhttp)可以直接下沉到基础库module中，直接使用，或者另写一个module，用组件服务接口对外暴露特定业务，隐藏实现，这样更加规范，比如说切换glide或者Picasso对于项目的影响几乎为0。

**Comment by leobert-lan** [comment]
其实对于UIrouter的实现我并不太满意。

其实正常路数应该是使用组件服务接口来隔离的(不过严格意义上讲，组建对象模型对外暴露的服务接口给组件内部使用不太像样)，不过比较“啰嗦”，所以我当时提供了uirouter。

对于一些常见的lib(glide，okhttp)可以直接下沉到基础库module中，直接使用，或者另写一个module，用组件服务接口对外暴露特定业务，隐藏实现，这样更加规范，比如说切换glide或者Picasso对于项目的影响几乎为0。

**Comment by YummyLau** [comment]
不过严格意义上讲，组建对象模型对外暴露的服务接口给组件内部使用不太像样
---------------------------------------------------------------------------
其实也可以所有组件要暴露的东西统一继承一个IComponentService，组件实现类用注解，然后运行时读取实现类统一反射注入也是可以。
微信用的是api话，是否有研究过呢
