### ISSUE TITLE
這個專案 gradle 版本？

### ISSUE THREAD

**Issue by lowfiend** [mqzhangw/JIMU#38]
我用 gradle-4.6-all 是無法使用的

Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectPublication.<init>(Lorg/gradle/api/artifacts/ModuleVersionIdentifier;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 0s
Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectPublication.<init>(Lorg/gradle/api/artifacts/ModuleVersionIdentifier;)V'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

去查了所用的
android-maven-gradle-plugin:1.5

https://github.com/dcendents/android-maven-gradle-plugin/issues/66
要升級 2.1
但是
升級完會出現
* Where:
Script '/Users/loverfiend/Desktop/project/JIMU/jimu-core/installv1.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'api' not found.

所以想問一下這專案gradle本版是使用啥
看起來4.6 跑不起來

**Comment by leobert-lan** [comment]
seems like you are using version 4.6 of gradle-wrapper (you can check it in the project-root/gradle/gradle-wrapper.properties).

But i think it is caused by other reason except gradle-wrapper for this issue. 

check if there is any network error such as 'sslexception','read time out','could not find host for XXXX'

**Comment by lowfiend** [comment]
I appreciate your message.
I downgrade gradle-wrapper 4.6 to 3.3, then it run as well.

**Comment by LinHongbo** [comment]
gradle版本：5.1.1->3.3
ndk版本：r18b->r15c
在Android studio 3.4 版本，可以通过编译
