### ISSUE TITLE
Gradle插件与uploadArchives  

### ISSUE THREAD

**Issue by duanmaoxu** [mqzhangw/JIMU#39]
在组件里  build.gradle 里使用了我们自定义的Gradle插件  再使用uploadArchives   无法上传aar包到maven服务器   显示任务执行完成但是实际没有成功。uploadArchives的相关任务都没有执行，请问 怎么解决呢？

**Comment by leobert-lan** [comment]
这是设计上的一个缺陷，此时应用的插件是com.android.application，需要对插件做一定的“任务适配”
