### ISSUE TITLE
You have duplicate classes with the same name : android.support.design.widget.CoordinatorLayout$1 please remove duplicate classes 

### ISSUE THREAD

**Issue by duantao561** [mqzhangw/JIMU#40]
classpath 'com.android.tools.build:gradle:3.1.4'
gradle 4.4报这个错误
You have duplicate classes with the same name : android.support.design.widget.CoordinatorLayout$1 please remove duplicate classes

**Comment by leobert-lan** [comment]
可以使用dependencies以及dependencyInsight检查申明的依赖。可能是多个不同版本的support包导致的。整理下依赖应该可以解决问题。

**Comment by leobert-lan** [comment]
时间过去太久了。如果还有出现的话，请新建issue，最好提供一个能复现的demo项目。
