### ISSUE TITLE
引入相关配置后，启动某个组件报了如下错误

### ISSUE THREAD

**Issue by Yifpro96** [mqzhangw/JIMU#45]
![](http://ww1.sinaimg.cn/large/d2a6e695gy1fw5smk6jy8j21eq0hpwhh.jpg)

**Comment by leobert-lan** [comment]
看起来项目中使用了kotlin，如果有使用kotlin的话，更安全的声明注解处理器的方式是使用kapt而不是annotationProcessor，因为后者的申明方式不会对kotlin中的注解进行处理。而前者是兼容的。
