### ISSUE TITLE
compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by xuexiansen** [mqzhangw/JIMU#47]
conponent以application编译之后，再编译app，就会出现以下错误，有遇到过吗？

* What went wrong:
Execution failed for task '::compileDebugJavaWithJavac'.
> Unable to find source java class: '/src/main/runalone/java/com/runalone/application/Application.java' because it does not belong to any of the source dirs: '[/Users/admin/src/main/java, /Users/admin/src/main/java, /Users/admin/src/debug/java, /Users/admint/build/generated/source/r/debug, /Users/admint/build/generated/source/buildConfig/debug, /Users/admint/build/generated/source/aidl/debug, /Users/admin/build/generated/source/rs/debug]'

**Comment by leobert-lan** [comment]
一般我都是以完整命令执行的：
gradle :{module name}:{task name},暂时没有遇到这种情况。
