### ISSUE TITLE
关于集成最终打包apk问题。

### ISSUE THREAD

**Issue by rijcm** [mqzhangw/JIMU#48]
我是将module打包aar文件，在app里面引用。
1：最后集成打包成最终的apk时候，安装会生成两个或多个应用，一个是app，一个是module应用。
2：module的名字还和app的一样，好像被app的名字代替了，我明明在module里面写的是module的名字。

**Comment by liruixing** [comment]
> 第一点看着像是你在非runalone包的清单文件中添加了多个
> 
> ```
> <category android:name="android.intent.category.LAUNCHER"/>
> ```

我是题主同事，您描述的对，这个现状很像添加了android.intent.category.LAUNCHER     但是排查过......确实没有这个情况

**Comment by leobert-lan** [comment]
看了下你脱敏后的项目；cashloan/src/main/AndroidManifest.xml 确实多配置了Launcher

**Comment by leobert-lan** [comment]
这一块确实比较麻烦，不管是建立模板文件还是检查配置。有时间、有机会的话我会考虑写个ide的插件，但是插件也难以避免配置出错的问题。
