### ISSUE TITLE
在app gadle.properties  中compileComponent=module名字时，一直报这个错，看了下demo，没有找到问题，希望得到解决

### ISSUE THREAD

**Issue by yangyoupeng** [mqzhangw/JIMU#51]
Unable to find source java class: 'E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\src\main\runalone\java\com\zkb\homepage\application\HomePageActivityModule.java' because it does not belong to any of the source dirs: '[E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\src\main\java, E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\src\debug\java, E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\build\generated\source\r\debug, E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\build\generated\source\buildConfig\debug, E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\build\generated\source\aidl\debug, E:\zkb\zMall\trunk\code\ZkbAndroid\zkb\homepage\build\generated\source\rs\debug]'

**Comment by yangyoupeng** [comment]
这个是在集成模式下，出现的问题

**Comment by leobert-lan** [comment]
对于非主module组件，建议用gradle命令打包，如果还有问题，希望提供更详细的信息，例如包结构，配置等。 最近太忙疏于维护，见谅。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
