### ISSUE TITLE
Gradle报错，我的Gradle版本是4.6，项目里的各个插件版本需要更新了吧

### ISSUE THREAD

**Issue by JakieTang** [mqzhangw/JIMU#53]
Unable to find method 'org.gradle.api.internal.artifacts.ivyservice.projectmodule.DefaultProjectPublication.<init>(Lorg/gradle/api/artifacts/ModuleVersionIdentifier;)V'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by adaJQD** [comment]
遇到同样的问题

**Comment by adaJQD** [comment]
@JakieTang 使用 gradle 3.3 可以通过编译

**Comment by leobert-lan** [comment]
没毛病，确实是插件中用的agp太老。
