### ISSUE TITLE
配置了android:launchMode="singleTask"，Autowired注解的变量在openUri后不会赋值

### ISSUE THREAD

**Issue by liyujiang-gzu** [mqzhangw/JIMU#61]
配置了android:launchMode="singleTask"，Activity再次打开不会走onCreate，只会走onNewInent，Autowired注解的变量在openUri后不会赋值，有没有什么办法解决？

**Comment by leobert-lan** [comment]
在onnewintent中再调用一次注入，注意先setintent


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
