### ISSUE TITLE
如果改成mvp模式

### ISSUE THREAD

**Issue by zgc2537** [mqzhangw/JIMU#62]
如果把reader模块改成mvp模式，reader模块在主app模块的activity中，那activity怎么初始化presenter，还是将presenter初始化放到fragment里

**Comment by leobert-lan** [comment]
这其实是一个经验性问题，没有严格的标准。我们说组建是可以独立的，那么完全可以将activity，fragment，presenter等全放在一个组件模块中，那么就没有你现在的代码隔离问题，至于是activity来操作f和p的初始化以及依赖注入还是fragment自己处理见仁见智，维护的成本都是可接受的。

如果确实有特殊原因activity需要放在主组件中，那么单fragment页面控制presenter的实例化会来的简单点，多fragment页面情况呢，把presenter接口或者抽象类下沉，由组件控制p的实例化，并通过service接口暴露方法给客户调用，由activity控制依赖注入，相对而言维护成本较小。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
