### ISSUE TITLE
组件单独调试问题

### ISSUE THREAD

**Issue by oywjAndroid** [mqzhangw/JIMU#64]
组件单独调试时，runalone下的application的onCreate方法未执行是什么问题？

**Comment by adaJQD** [comment]
检查下`/runalone`目录下是否创建了`AndroidManifest.xml`，并且在其`application`标签中指向自定义`application`

**Comment by oywjAndroid** [comment]
这个问题后来发现是组件下的build.gradle中没有添加：`javaCompileOptions {
            annotationProcessorOptions {
                arguments = [host: "register"]
            }
        }`
