### ISSUE TITLE
我怎么运行不起来呢

### ISSUE THREAD

**Issue by mrme2014** [mqzhangw/JIMU#67]
导入的是 这个工程  jimu-sample-project

jimu-core这个工程是干嘛的

**Comment by leobert-lan** [comment]
jimu-sample-project 是演示如何使用JIMU以组件化形式搭建项目的，其中也包含了如何使用JIMU中提供的简易路由、JIMU中提供的可支持同应用跨进程的消息中间件、使用Module中Butterknife、使用Arouter作为路由等；
jimu-core工程是JIMU的核心，包括：gradle构建插件、JIMU简易路由、JIMU消息中间件等内容；

考虑到项目内容较多而很大一部分开发者是刚接触JIMU，更重要的是弄清楚如何使用JIMU做组件化，全部揉在一起会很混乱，所以拆分了项目，如果是运行的Master或Dev分支，其中jimu-sample依赖的lib版本不一定是发布版，需要先将jimu-core中的内容全部发布到本地，或者参考release修改依赖依赖的lib版本。

注意本地的环境最好和sample中使用的一致。
