### ISSUE TITLE
能否提供环境

### ISSUE THREAD

**Issue by JDongKhan** [mqzhangw/JIMU#68]
能否提供源码的环境配置，比如gradle版本，Android plugin版本，各种报错。 谢谢。

**Comment by xiaojinzi123** [comment]
> 能否提供源码的环境配置，比如gradle版本，Android plugin版本，各种报错。 谢谢。

[Component](https://github.com/xiaojinzi123/Component) 可以使用这个方案,对系统没有任何的更改,代码全透明,并且拓展了很多歌好用的功能
