### ISSUE TITLE
关于isRegisterCompoAuto及RegisterCompManual的疑问

### ISSUE THREAD

**Issue by liyujiang-gzu** [mqzhangw/JIMU#70]
1、com.dd.comgradle的combuild.isRegisterCompoAuto配置为false，为何还强制同时配置combuild.applicationName呢？不配置applicationName项目就会构建失败。<br />
2、combuild.isRegisterCompoAuto配置为false的时候，是否必须要为IApplicationLike的实现类加上RegisterCompManual注解？

**Comment by liyujiang-gzu** [comment]
combuild.isRegisterCompoAuto配置为false的时候，IApplicationLike的实现类的RegisterCompManual注解不是必须要加的：

>>>> javassist.CtClassType@262c7fb2[public class xxx.browser.BrowserAppLike implements com.luojilab.component.componentlib.applicationlike.IApplicationLike,  fields= constructors=javassist.CtConstructor@7eacaec5[public BrowserAppLike ()V],  methods=javassist.CtMethod@119b79fc[public onCreate ()V], javassist.CtMethod@59c8eb42[public onStop ()V], ] **manual register?false**
Application is   runalone.BrowserApplication
ApplicationLike will be auto register: xxx.browser.BrowserAppLike
>>>
>>>
>>>
>>>
check isRegisterCompoAuto:  W:\xxx\build\intermediates\javac\debug\compileDebugJavaWithJavac\classes ; **isRegisterCompoAuto:false**

**Comment by YummyLau** [comment]
实际上我更倾向于 调试独立不耦合在组件内，无需走反射直接调试就好了。
可以参考  https://github.com/YummyLau/ComponentPlugin

**Comment by liyujiang-gzu** [comment]
> 实际上我更倾向于 调试独立不耦合在组件内，无需走反射直接调试就好了。
> 可以参考 https://github.com/YummyLau/ComponentPlugin

学习了，站在巨人的肩上走的更远

**Comment by leobert-lan** [comment]
*抱歉时隔两年才答复。*

插件配置组件入口（applicationName）是最开始的方案，后来我参与了项目，个人认为方案中的一些做法**虽然简单但不简便**。所以计划尝试 `利用Gradle Transformer 阶段扫描` 做 `组件发现` 取代 `组件配置`，出于个人精力受限，印象中整个计划没有全部做完，给大家带来了一些困扰。

* applicationName 配置runalone时Application的入口，这一点没有变
* combuild.isRegisterCompoAuto 意指：runalone时是否织入 ”组件的初始化代码“，但原始方案中，无法对加载顺序，加载时机做任何干涉。

为了解决这些问题，计划中分了几步：
* 先建立排除机制，让指定的组件无法被自动加载，即添加 `RegisterCompManual`注解
* 添加一个支持库，让组件的加载可被描述为 ”一系列存在依赖条件的任务“，按照任务图处理加载，_这部分工作作为Maat项目单独发布了_。这样IApplicationLike就是一个单纯的 `注入点`, 用于向加载任务中注入 ”组件初始化逻辑“
* 废除 combuild.isRegisterCompoAuto 等机制，在前面的步骤完成后，我们可以激进的认为：”除了无须自动加载的组件，均可以被自动加载 “（当然，这个想法一定存在争议：是组件决定自己是否应该被加载，还是宿主决定是否自动加载组件）_这一步尚未实施_
