### ISSUE TITLE
导入项目的时候报错，大达们怎么解决

### ISSUE THREAD

**Issue by q2690962** [mqzhangw/JIMU#71]
ERROR: Cause: tried to access method org.gradle.api.internal.artifacts.DefaultModuleVersionIdentifier.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V from class org.gradle.api.plugins.AndroidMavenPlugin$8

**Comment by wuxianghua** [comment]
我也遇到了，你解决了么

**Comment by Android500** [comment]
没法整

**Comment by xiaojinzi123** [comment]
貌似项目不维护了,新来的可以使用更强大的 [Component](https://github.com/xiaojinzi123/Component)

**Comment by zhaoweiguo5505** [comment]
我也遇到了 解决了吗？

**Comment by leobert-lan** [comment]
目前的demo中应该已经OK了。这类一般都是AGP和Gradle版本不适配所致，插件中依赖了AGP。
