### ISSUE TITLE
项目运行不起来解决方案

### ISSUE THREAD

**Issue by lhholylight** [mqzhangw/JIMU#74]
项目运行不起来是因为gradle版本过高，
1.请将gradle版本降到3.3
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
2.禁用 Only sync the active variant
You can disable this experimental feature from
File → Settings → Experimental → Gradle → Only sync the active variant

**Comment by xiaojinzi123** [comment]
貌似项目不维护了,新来的可以使用更强大的 [Component](https://github.com/xiaojinzi123/Component)

**Comment by leobert-lan** [comment]
应该是那时候的agp版本较低所致。

对于gradle插件，我个人建议还是需要二次维护的，毕竟不同的团队的项目环境还是有差别的。
