### ISSUE TITLE
JIMU升级到1.3.5的时候出错

### ISSUE THREAD

**Issue by duxingzhe** [mqzhangw/JIMU#79]
Execution failed for task ':app:runaloneMergeAppjingjirenDebugManifest'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class java.lang.String]
  	[class java.net.URI]

我应该如何解决这个问题？如果这个问题无法解决，我就用不了最新版本的kotlin。我查了gradlew，发现和gson的反射有冲突，该如何解决这个问题。

**Comment by leobert-lan** [comment]
推测是配置的原因。需要配置 原始，runalone，合并输出的manifest，三个目录，参考下demo。

**Comment by leobert-lan** [comment]
推测是配置的原因。需要配置 原始，runalone，合并输出的manifest，三个目录，参考下demo。

**Comment by duxingzhe** [comment]
解决了，谢谢你的帮助。
