### ISSUE TITLE
1.3.5更新到mavenCentral后demo不能运行

### ISSUE THREAD

**Issue by wangltandroid** [mqzhangw/JIMU#80]
demo工程更新到最新版mavenCentral的地址后，报错找不到javassist.CannotCompileException，推测应该是提交到mavenCentral版本的build-gradle插件未处理好依赖的javassist的jar包，所以报错，请了解
`Unable to load class 'javassist.CannotCompileException'.

This is an unexpected error. Please file a bug containing the idea.log file.
`

**Comment by leobert-lan** [comment]
问题确实存在，我检查一下

**Comment by leobert-lan** [comment]
这下头大了，所有的pom文件都有问题。。。

**Comment by leobert-lan** [comment]
可能需要等到周末才能修复了，目前手边的电脑没有签名文件。。。

**Comment by wangltandroid** [comment]
感谢重视，贵团队的方案很好，对我很有帮助

**Comment by leobert-lan** [comment]
只能接一句：开源万岁

**Comment by leobert-lan** [comment]
抽了点时间先进行了一点补救，好歹收获了一些其他的知识，又激发了“秀操作”的灵感。

感谢指出问题，端午我抽时间处理下重新发版本。
